# Generated by Django 5.0.9 on 2026-08-13 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bedesk', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservarecurso',
            name='recurso',
        ),
        migrations.RemoveField(
            model_name='reservarecurso',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Recurso',
        ),
        migrations.DeleteModel(
            name='ReservaRecurso',
        ),
    ]
