# Generated by Django 5.0.9 on 2026-08-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedesk', '0006_remove_reservarecurso_recurso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='foto',
            field=models.ImageField(blank=True, help_text='Imagem exibida no card do local na listagem.', null=True, upload_to='salas/', verbose_name='Foto do local'),
        ),
    ]
