# Generated by Django 5.2.7 on 2026-07-22 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('RESERVA_CRIADA', 'Reserva criada'), ('RESERVA_APROVADA', 'Reserva aprovada'), ('RESERVA_REJEITADA', 'Reserva rejeitada'), ('RESERVA_CANCELADA', 'Reserva cancelada'), ('RECURSO_CRIADO', 'Solicitação de recurso'), ('RECURSO_APROVADO', 'Recurso aprovado'), ('RECURSO_REJEITADO', 'Recurso rejeitado'), ('LEMBRETE', 'Lembrete'), ('ADMIN_NOVA_SOLICITACAO', 'Nova solicitação'), ('CONFLITO_HORARIO', 'Conflito de horário'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=30)),
                ('link', models.CharField(blank=True, default='', max_length=300)),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criada_em'],
            },
        ),
    ]
