# Generated by Django 5.0.9 on 2026-08-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('RESERVA_CRIADA', 'Reserva criada'), ('RESERVA_APROVADA', 'Reserva aprovada'), ('RESERVA_REJEITADA', 'Reserva rejeitada'), ('RESERVA_CANCELADA', 'Reserva cancelada'), ('LEMBRETE', 'Lembrete'), ('ADMIN_NOVA_SOLICITACAO', 'Nova solicitação'), ('CONFLITO_HORARIO', 'Conflito de horário'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=30),
        ),
    ]
